Added srg to Morpheus Experimental
nv-morpheus/morpheus-experimental pull request #14
Opened 2022-10-27 21:58 UTC by shawn-davis

Initial Syslog Resemblance Grouping (SRG) addition to Morpheus Experimental.

2022-10-27 22:05 UTC, raykallen commented
closes https://github.com/nv-morpheus/morpheus-experimental/issues/15

2022-10-27 22:09 UTC, raykallen commented
/ok to test

2022-10-27 22:19 UTC, raykallen commented
/rerun tests

2022-10-28 12:33 UTC, raykallen commented
/ok to test

2022-10-28 13:21 UTC, raykallen commented
Can you also update the main [readme](https://github.com/nv-morpheus/morpheus-experimental/blob/branch-22.11/README.md) to include SRG?

2022-10-28 15:10 UTC, BartleyR commented on syslog-resemblance-grouping/README.md
> +# Syslog Resemblance Grouping - SRG
Minor tweak - but suggest this is:

Syslog Resemblance Grouping (SRG)

2022-10-28 15:10 UTC, BartleyR commented on syslog-resemblance-grouping/README.md
> +SRG is designed to find a subset of representative strings within a a large collection of messages. These representative strings create groupings with which to categorize the messages for further exp
Suggest changing to:

Syslog Resemblance Grouping (SRG) is designed to find a subset of representative strings within a a large collection of messages. These representative strings create groupings with which to categorize the messages for further exploration or triage.

2022-10-28 15:10 UTC, BartleyR commented on syslog-resemblance-grouping/README.md
> +### Technique Overview
Is there a graphic that illustrates this well (that exists, or is easily modified)? Could be nice to have here.

2022-10-28 15:10 UTC, BartleyR commented on syslog-resemblance-grouping/README.md
> +
@raykallen Do you want a section on how to run this? Example run command, etc.? I think it would be useful. Could also show expected input and output.

2022-10-28 16:38 UTC, shawn-davis commented on syslog-resemblance-grouping/README.md
> +
The API calls and usages are illustrated in the accompanying notebook. I can mention that here, if you want.

2022-10-28 18:26 UTC, shawn-davis commented on syslog-resemblance-grouping/README.md
> +### Technique Overview
Not a great one, no. I've used pie charts and sunbursts but most times they end up feeling very crowded. I've also projected the logs into a high dimensional space and then used UMAP to plot it in 2-dimensions and color by the SRG groups. It looks pretty, but doesn't ultimately provide additional insight into the data versus just looking at the group statistics in a table. I'll give it some more thought, though.

2022-10-28 18:27 UTC, shawn-davis commented on syslog-resemblance-grouping/README.md
> +SRG is designed to find a subset of representative strings within a a large collection of messages. These representative strings create groupings with which to categorize the messages for further exp
Changed. Thanks!

2022-10-28 18:29 UTC, shawn-davis commented on syslog-resemblance-grouping/README.md
> +# Syslog Resemblance Grouping - SRG
Changed.

2022-10-28 18:32 UTC, shawn-davis commented
> Can you also update the main [readme](https://github.com/nv-morpheus/morpheus-experimental/blob/branch-22.11/README.md) to include SRG?

I added a SRG blurb to the main README.

2022-10-28 19:02 UTC, raykallen commented on syslog-resemblance-grouping/README.md
> +
For now, let's just link the notebook as the example for how to run it. You can update it when there's a script to run from cli.

2022-10-31 19:13 UTC, raykallen commented
/ok to test

2022-10-31 19:23 UTC, raykallen approved these changes
lgtm

2022-10-31 19:41 UTC, mdemoret-nv requested changes
I started to review some of these changes but I have some suggestions which are more general so I will put them here:

1. Code commenting and spacing: In general, this code could really benefit from more comments and better spacing. I dont think I saw a single comment that is not a copyright header or unused code.
   2. Generally spacing and commenting go hand in hand. If you add comments into the code describing the logical steps in the algorithm, it will also help break up the massive blocks of code with no whitespace in them.
3. Why does every file start with an underscore? For example, `_srg.py`, `_fastkde.py`, etc.
4. There are no public docstrings on any files. At minimum, we should be documenting the major public interfaces (Class constructors, `fit` and `transform` methods, etc.). Users need this information to understand how these classes should, and should not, be used.

2022-10-31 20:32 UTC, BartleyR commented
@mdemoret-nv Had some questions:

> 1. Code commenting and spacing: In general, this code could really benefit from more comments and better spacing. I dont think I saw a single comment that is not a copyright header or unused code.

Do we want to enforce flake, pep, something else here? it may not be a bad idea.

> 3. There are no public docstrings on any files. At minimum, we should be documenting the major public interfaces (Class constructors, `fit` and `transform` methods, etc.). Users need this information to understand how these classes should, and should not, be used.

Agree with docstrings

2022-10-31 20:37 UTC, mdemoret-nv commented
> Do we want to enforce flake, pep, something else here? it may not be a bad idea.

@BartleyR I'm not sure of any tool that would reliably enforce code commenting or spacing in any reliable way. Adding something like this may cause more harm than good and could be easily gamed (You could add stuff like `# Just making the linter happy`). 

Good commenting and spacing is something that can really only be enforced via code reviews. Everything else (docstrings, naming conventions, etc.) can be easily automated.

2022-10-31 20:47 UTC, BartleyR commented
> > Do we want to enforce flake, pep, something else here? it may not be a bad idea.
> 
> @BartleyR I'm not sure of any tool that would reliably enforce code commenting or spacing in any reliable way. Adding something like this may cause more harm than good and could be easily gamed (You could add stuff like `# Just making the linter happy`).
> 
> Good commenting and spacing is something that can really only be enforced via code reviews. Everything else (docstrings, naming conventions, etc.) can be easily automated.

Understood. Sounds good.

2022-11-02 20:46 UTC, shawn-davis commented
> I started to review some of these changes but I have some suggestions which are more general so I will put them here:
> 
> 1. Code commenting and spacing: In general, this code could really benefit from more comments and better spacing. I dont think I saw a single comment that is not a copyright header or unused code.
>    2. Generally spacing and commenting go hand in hand. If you add comments into the code describing the logical steps in the algorithm, it will also help break up the massive blocks of code with no whitespace in them.
> 2. Why does every file start with an underscore? For example, `_srg.py`, `_fastkde.py`, etc.
> 3. There are no public docstrings on any files. At minimum, we should be documenting the major public interfaces (Class constructors, `fit` and `transform` methods, etc.). Users need this information to understand how these classes should, and should not, be used.

I've added docstrings to the public classes and methods. As far as the file naming conventions go, it's just the structure I've gone with. I add the public classes and methods to the __init__ to tighten up the imports when working with the classes and methods. Mainly, I just really dislike `from srg.srg import Srg` in favor of `from srg import Srg`.

2022-11-02 21:03 UTC, BartleyR commented
> As far as the file naming conventions go, it's just the structure I've gone with. I add the public classes and methods to the **init** to tighten up the imports when working with the classes and methods. Mainly, I just really dislike `from srg.srg import Srg` in favor of `from srg import Srg`.

Looking forward to when this eventually goes into Morpheus, what do the imports look like there? Does core functionality become `from morpheus.srg import Srg`, or like `from morpheus.analytics.srg import Srg`?

2022-11-07 17:04 UTC, BartleyR commented
/ok to test

2022-11-10 18:29 UTC, mdemoret-nv approved these changes
While it's certainly and improvement, there is more that could be done to improve the code's maintainability log term. Approving since this is experimental

2022-11-10 18:30 UTC, mdemoret-nv commented
> LGTM. @mdemoret-nv can you give this a quick look so we can merge?

@BartleyR Approved. Ready to be merged once the conflict has been resolved.

2022-11-14 15:02 UTC, raykallen commented
@gpucibot merge

2022-11-14 15:02 UTC, merged