[WIP] rgcn-authentication detection
nv-morpheus/morpheus-experimental pull request #17
Opened 2022-11-04 18:56 UTC by tzemicheal

This closes
https://github.com/nv-morpheus/Morpheus/issues/218

2022-11-07 16:11 UTC, BartleyR reviewed
The code (specifically the `.py` files) needs more inline documentation.

2022-11-08 14:42 UTC, shawn-davis commented
lgtm

2022-11-08 15:11 UTC, raykallen requested changes
for the notebook: intro needs to include why rgcn over traditional graph methods and rules-based methods. What is the motivation?
Include rational for using the status flag for training
List the features used for OHE in the authentication node and lack of OHE features in other nodes
Graph the results for the synthetic dataset. Discuss what makes them different from the internal dataset. Suggest what attributes make a good dataset for this technique.

2022-11-08 15:12 UTC, raykallen commented
Please add blurb with link on the main repo readme here: https://github.com/nv-morpheus/morpheus-experimental#current-cybersecurity-workflow-prototypes

2022-11-08 20:05 UTC, BartleyR commented on malicious-authentication-detection/README.md
> +
Yes. Add any pre-reqs for a dataset that would make it amenable to this approach.

2022-11-08 20:12 UTC, BartleyR requested changes
Comments on the notebook:

- The notebook is missing a motivation - i.e., why did we even do this in the first place? Although this may be better placed in the `README.md`. Unless you have a preference @raykallen , I'd like this placed in the `README.md` and can just be summarized/replicated in the notebook.
- Why not make the references hot-linked? Would be much easier to follow them.
- Write a few sentences explaining the image (results) shown in the Evaluation section

2022-11-08 20:12 UTC, BartleyR commented on malicious-authentication-detection/README.md
> +This model shows an application of a graph neural network for malicious authentication detection in Azure-AD signon heterogeneous graph. An Azure-AD signon dataset  includes four types of nodes, auth
Is it possible to link to more information about Azure-AD online? Are there resource pages from MSFT?

2022-11-08 20:12 UTC, BartleyR commented on malicious-authentication-detection/README.md
> +V100
Which version?

2022-11-08 20:13 UTC, BartleyR commented on malicious-authentication-detection/README.md
> +This model shows an application of a graph neural network for malicious authentication detection in Azure-AD signon heterogeneous graph. An Azure-AD signon dataset  includes four types of nodes, auth
I see the link in the notebook. We should make sure we're presenting all of the salient information on GitHub, since that will be the first landing site.

2022-11-08 20:21 UTC, tzemicheal commented on malicious-authentication-detection/README.md
> +
I will update the readme.

2022-11-08 20:23 UTC, tzemicheal commented on malicious-authentication-detection/README.md
> +
A threshold of 0.499 is used to output failure/success. It has the option to output as `test_log.argmax(dim=1)`

2022-11-08 22:20 UTC, tzemicheal commented on malicious-authentication-detection/README.md
> +V100
Fixed this in the new revision.

2022-11-09 01:54 UTC, hsin-c commented on malicious-authentication-detection/README.md
> +Detection of Malicious Accounts on Azure-AD signon using Relational Graph Neural Network (RGCN)
Are we detecting malicious account or authentication? (or both? the title suggests authentication but this line suggests otherwise)
Also, is this model detection "malicious" behavior or "anomalous" behavior? (or error-prone behavior?) We seem to be using those interchangeably in this readme, but I feel like detecting "malicious" is a much heavier lift as security expertise would often be required (hence hard to achieve by unsupervised or semisupervised methods).

2022-11-09 15:18 UTC, tzemicheal commented on malicious-authentication-detection/README.md
> +Detection of Malicious Accounts on Azure-AD signon using Relational Graph Neural Network (RGCN)
> Are we detecting malicious account or authentication? (or both? the title suggests authentication but this line suggests otherwise) Also, is this model detection "malicious" behavior or "anomalous" behavior? (or error-prone behavior?) We seem to be using those interchangeably in this readme, but I feel like detecting "malicious" is a much heavier lift as security expertise would often be required (hence hard to achieve by unsupervised or semisupervised methods).

The primary task is the detection of malicious authentication, all the metric is done on authentication. For user detection, the authentications are aggregated across authentication made by a user(e.g. in the experiment I took the median scores of all authentication made for each user per timestamp), based on this user detection is a summarized part of the authentication detection. 

For the second point, the goal of this use case is to detect malicious users. I agree we have been using the word interchangeable. In my opinion, malicious behavior is a subset of anomalous behavior. Technically, we trained the model to identify "failure" cases, which could be either abnormal or malicious. But, the evaluation is done on test data that is simulated to act as malicious behavior (synthetic dataset) or internal result reported.

2022-11-09 18:23 UTC, tzemicheal commented on malicious-authentication-detection/training-tuning/model.py
> +class HeteroRGCNLayer(nn.Module):
Fixed this script.

2022-11-09 18:54 UTC, BartleyR commented on malicious-authentication-detection/README.md
> +Detection of Malicious Accounts on Azure-AD signon using Relational Graph Neural Network (RGCN)
This is more anomalous (like Hsin mentioned) than malicious, right? Something can be anomalous and not be malicious. But I don't think we're specifically classifying intent here.

2022-11-09 20:38 UTC, tzemicheal commented on malicious-authentication-detection/README.md
> +Detection of Malicious Accounts on Azure-AD signon using Relational Graph Neural Network (RGCN)
Updated the README/NB. Thanks.

2022-11-10 14:19 UTC, raykallen approved these changes
lgtm

2022-11-10 17:50 UTC, BartleyR approved these changes
LGTM

2022-11-10 17:50 UTC, BartleyR commented
/ok to test

2022-11-10 17:56 UTC, raykallen commented
@gpucibot merge

2022-11-10 17:56 UTC, merged