operational-technology-use-case
nv-morpheus/morpheus-experimental pull request #35
Opened 2023-02-10 13:58 UTC by gbatmaz

Operational technology use case notebook, scripts and an example model.

2023-02-22 19:45 UTC, tzemicheal requested changes
I added few comments to OT PR, thanks.

Could you add title & info of the usecase at the main [README](https://github.com/gbatmaz/morpheus-experimental/blob/ot/README.md) file for the operational technology usecase

2023-02-22 19:45 UTC, tzemicheal commented on operational-technology/training-tuning/ot-xgboost-train.py
> +    with open(modelname, "wb") as file:
I wonder if you have tested the  XGBoostClassifier `save_model & load_model` method to save & restore model, instead of pickle. It could be easier to handle the versioning issue due to pickle.

2023-02-22 19:45 UTC, tzemicheal commented on operational-technology/inference/ot-xgboost-inference.py
> +    with open(model, "rb") as file:
Same as training script with load_model method instead of pickle load.

2023-02-22 19:45 UTC, tzemicheal commented on operational-technology/training-tuning/ot-xgboost-20230207.ipynb
> +    "xgb_clf = XGBClassifier(n_estimators=1000)"
It could be helpful if you include the training parameters of XGBoost as variables. I read you have already mentioned in the readme file (copying from it) `{'subsample': 0.8, 'n_estimators': 1200, 'min_child_weight': 2, 'max_depth': 20, 'learning_rate': 0.15, 'gamma': 0.5, 'colsample_bytree': 0.1}`

2023-02-24 12:10 UTC, gbatmaz commented on operational-technology/inference/ot-xgboost-inference.py
> +    with open(model, "rb") as file:
Thank you for the feedback. When I tested, the file saved with the save_model was missing some attributes. Hence chose to use the pickle version.

2023-02-24 12:11 UTC, gbatmaz commented on operational-technology/training-tuning/ot-xgboost-20230207.ipynb
> +    "xgb_clf = XGBClassifier(n_estimators=1000)"
The hyperparameter optimisation steps would take up massive space in the notebook, so we chose to leave the details in the Readme and use most of the default parameters in the code.

2023-02-24 12:12 UTC, gbatmaz commented
> I added few comments to OT PR, thanks.
> 
> Could you add title & info of the usecase at the main [README](https://github.com/gbatmaz/morpheus-experimental/blob/ot/README.md) file for the operational technology usecase

Thank you! Just pushed a commit for this

2023-02-24 15:01 UTC, tzemicheal approved these changes

2023-02-24 15:12 UTC, tzemicheal commented
LGTM!

2023-02-24 15:56 UTC, raykallen requested changes

2023-02-24 16:31 UTC, gbatmaz commented on operational-technology/README.md
> +The model is an XGBoost classifier that predicts each event on a power system based on dataset features.
I have added multi-class now

2023-02-24 16:31 UTC, gbatmaz commented on operational-technology/README.md
> +
Added  "how to use this model", "input data", and "output" sections to readme

2023-02-24 16:32 UTC, gbatmaz commented on operational-technology/README.md
> +The label distribution in the dataset is not imbalanced, so we do not use the accuracy score. Instead, we use F1 weighted as the metric. The F1 score was over 0.91 on a test set.
fixed that

2023-02-24 18:47 UTC, raykallen approved these changes
lgtm

2023-02-24 18:50 UTC, raykallen commented
/merge

2023-02-24 18:50 UTC, merged