[REVIEW] cyber foundation notebook and scripts
nv-morpheus/morpheus-experimental pull request #77
Opened 2024-06-12 22:52 UTC by gbatmaz

## Description
Cyber foundation notebook, model and scripts that can learn from raw cyber logs and generate synthetic logs which can be used for various downstream tasks

2024-06-13 12:52 UTC, hsin-c commented on cyber-foundation/dataset/azure-ad-logs-sample-training-data.json
Add a readme for the dataset in this same folder (can copy from morpheus proper)

2024-06-13 13:58 UTC, tzemicheal commented on cyber-foundation/training-inference/train.py
> +# # logging
Clean unused comments.

2024-06-13 14:01 UTC, tzemicheal commented on cyber-foundation/training-inference/prepare.py
> +    return [stoi[c] for c in s]  # encoder: take a string, output a list of integers
-rearrange the comment "encoder: takes ..." above the `return` line

2024-06-13 14:01 UTC, tzemicheal commented on cyber-foundation/training-inference/prepare.py
> +    return ''.join([itos[i] for i in sequence])  # decoder: take a list of integers, output a string
Same like above

2024-06-13 14:05 UTC, tzemicheal requested changes
Overall, the code LGTM! I understand the usecase depends on third party codes. Would be nice if the comments are rearranged for some of the codes in the scripts.

2024-06-13 18:30 UTC, gbatmaz commented on cyber-foundation/dataset/azure-ad-logs-sample-training-data.json
Done Thank you

2024-06-13 18:49 UTC, tzemicheal commented on cyber-foundation/training-inference/train.py
> +# # logging
Will be updated later

2024-06-13 19:56 UTC, tzemicheal approved these changes

2024-06-14 06:17 UTC, hsin-c commented on cyber-foundation/README.md
> +* This model output can be used as a binary result, DGA or Benign
Is this off?

2024-06-14 06:17 UTC, hsin-c commented on cyber-foundation/dataset/README.md
> +## Cyber Foundation Model Data
We could add a link to morpheus proper too for this identical dataset

2024-06-14 06:17 UTC, hsin-c commented on cyber-foundation/training-inference/cyber-foundation.ipynb
> +    "2. Generating attack behaviour to test detectors:**\n",
Is this extra **?

2024-06-14 06:17 UTC, hsin-c commented on cyber-foundation/training-inference/cyber-foundation.ipynb
> +    "In our experiments with real logs, 90% of the generated logs were intact.\n",
"the generated logs were intact."-- intact sounds 
a bit misleading, like it's reproducing what's in the training set. Maybe we can say it's in parsable json format?

2024-06-14 07:56 UTC, gbatmaz commented on cyber-foundation/training-inference/cyber-foundation.ipynb
> +    "In our experiments with real logs, 90% of the generated logs were intact.\n",
Great point. Thanks for the feedback! Updated now.

2024-06-14 08:20 UTC, gbatmaz commented
thank you both! I've addressed all the comments @hsin-c Could you please approve and merge?

2024-06-14 08:22 UTC, hsin-c approved these changes
LGTM

2024-06-14 08:25 UTC, hsin-c commented
/merge

2024-06-14 08:25 UTC, merged